name: Auto triggered JUnit5 tests on Linux with Chrome

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'   

    - name: Install Chrome for Linux Ubuntu
      uses: browser-actions/setup-chrome@v1
      with:
        install-dependencies: true

    - name: Run tests with Maven
      working-directory: ${{ github.workspace }}
      run: mvn clean test