name: Automatically triggered JUnit5 tests by push on matrix OS and Browsers

on:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        browser: [chrome, firefox, edge]
        exclude:
          - os: ubuntu-latest
            browser: edge
          - os: macos-latest
            browser: edge

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Install Chrome (Linux)
      if: matrix.browser == 'chrome' && runner.os == 'Linux'
      uses: browser-actions/setup-chrome@v1
      with:
        install-dependencies: true

    - name: Install Chrome (non-Linux)
      if: matrix.browser == 'chrome' && runner.os != 'Linux'
      uses: browser-actions/setup-chrome@v1

    - name: Set Chrome options as env var
      if: matrix.browser == 'chrome'
      run: echo "CHROME_ARGS=--headless=new --no-sandbox --disable-dev-shm-usage --user-data-dir=/tmp/profile-$RANDOM" >> $GITHUB_ENV

    - name: Install Firefox
      if: matrix.browser == 'firefox'
      uses: browser-actions/setup-firefox@v1

    - name: Install Edge
      if: matrix.browser == 'edge'
      uses: browser-actions/setup-edge@v1
      with:
        edge-version: 'stable'

    - name: Run tests with Maven
      working-directory: ${{ github.workspace }}
      run: |
        PROFILE_ID="profile-${{ github.run_id }}-${{ matrix.os }}-${{ matrix.browser }}"
        if [ "${{ matrix.browser }}" = "chrome" ]; then
          mvn clean test -Dbrowser=chrome -Dchrome.args="--headless=new --no-sandbox --disable-dev-shm-usage --user-data-dir=/tmp/$PROFILE_ID"
        elif [ "${{ matrix.browser }}" = "firefox" ]; then
          mvn clean test -Dbrowser=firefox -Dfirefox.args="--headless --profile /tmp/$PROFILE_ID"
        else
          mvn clean test -Dbrowser=edge
        fi