name: Run JUnit5 Tests on Windows

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          
      - name: Show directory content (debug)
        run: dir
      
      - name: Run tests with Maven from src folder
        run: mvn -f D:/a/Automation/Automation/src/pom.xml clean test
